# Generated by Django 4.1.2 on 2022-10-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='receive_by',
            new_name='receive_books',
        ),
    ]
